Demo/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :mailboxes

  resources :admins, only: :index
  resources :mailboxes
  resources :emails
  
  devise_scope :mailbox do
    root "devise/sessions#new"
  end
end

Demo/app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

Demo/app/models/attachment.rb
# Fixed: remove Polymorphic association, no need
# Fixed: convert_to_spam_email method in validation
class Attachment < ActiveRecord::Base
  belongs_to :email

  validates :filename, :type, :email_id, presence: true
  validate :convert_to_spam_email, if: Proc.new { |attachment| attachment.type == 'Text'}

# save email to spam if attachement is type = 'Text'
  def convert_to_spam_email
    email = Email.find(email_id)
    email.spam = true
    email.save
  end
end

Demo/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :mailbox_one, class_name: Mailbox
  belongs_to :mailbox_two, class_name: Mailbox

  validates :firstname, :lastname, :phone_number, :address, presence: true
  validates :phone_number, length: { is: 10 }
  validates :mailbox_one_id, uniqueness: { scope: :mailbox_two_id }
end

Demo/app/models/email.rb
# Fixed: class name from EMail to Email.
# Fixed: attachment gets destroy if emails get deleted.

class Email < ActiveRecord::Base
  belongs_to :mailbox, foreign_key: 'sender_mailbox_id'
  has_and_belongs_to_many :mailboxes, association_foreign_key: 'receiver_mailbox_id'
  has_many :attachments, dependent: :destroy
  
  validate :count_in_mailbox_less_than_three?, on: :create
  
  define_model_callbacks :sending
  before_save :check_count_of_total_recipients_less_than_3?
  before_save :add_default_subject, if: Proc.new { |mail| mail.subject.nil? }
  after_create :add_contact

# custom callback
  def sending
    ActiveRecord::Base.transaction do
      run_callbacks :sending do
        insert_details_to_log
      end
    end
  end

  private
# adding default subject value 
  def add_default_subject
    self.subject = 'IMPORTANT!!!'
  end

# maximum no of mails in a mailbox be 3
  def count_in_mailbox_less_than_three?
    mailbox = Mailbox.find(sender_mailbox_id)
    if mailbox.mails.count > 2
      errors[:base] << 'Mailbox cannot have more than 2 mails'
    end
  end

# inserting the mailing info to the log
  def insert_details_to_log
    mailbox = Mailbox.find(self.sender_mailbox_id)
    log = Log.create(information: "#{ mailbox.firstname } send email with subject #{ self.subject }")
  end

# maximum number of recipients be 3
  def check_count_of_total_recipients_less_than_3?
    mailboxes.size <= 3
  end

  def add_contact
    mailbox_array = mailboxes
    mailbox_array.each do |mailbox|
      Contact.create(firstname: mailbox.firstname, lastname: mailbox.lastname, mailbox_one_id: mailbox.id, mailbox_two_id: sender_mailbox_id)
    end
  end
end

Demo/app/models/image.rb
class Image < Attachment
end

Demo/app/models/log.rb
class Log < ActiveRecord::Base
end

Demo/app/models/mailbox.rb
# Fixed: added dependent=> :destroy 
class Mailbox < ActiveRecord::Base
  has_many :mails, class_name: Email, foreign_key: 'sender_mailbox_id', dependent: :destroy
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  # using association extension
  has_many :mails, class_name: Email, foreign_key: 'sender_mailbox_id', dependent: :destroy do
    def find_spam_mails
      find_by(spam: true)
    end
  end
  has_and_belongs_to_many :emails, foreign_key: 'receiver_mailbox_id'

  has_many :contacts_one, class_name: Contact, foreign_key: :mailbox_one_id, dependent: :destroy
  has_many :mailboxes_one, class_name: Mailbox, through: :contacts_one, source: :mailbox_one
  has_many :contacts_two, class_name: Contact, foreign_key: :mailbox_two_id, dependent: :destroy
  has_many :mailboxes_two, class_name: Mailbox, through: :contacts_two, source: :mailbox_one
  
  validates :firstname, :lastname, :email, presence: true
  validates :score, numericality: { only_integer: true, less_than_or_equal_to: 5 }
  validates :email, uniqueness: { case_sensitive: false }

  before_destroy :destroy_if_no_non_spam_email?, prepend: true
  
  private
# destroy mailbox if there is no non-spam mails
  def destroy_if_no_non_spam_email?
    mails.all? { |mail| mail.spam }
  end
  

end

Demo/app/models/text.rb
class Text < Attachment
end

Demo/app/models/video.rb
class Video < Attachment
end

Demo/app/models/zip.rb
class Zip < Attachment
end

Demo/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

Demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admins_url
  end

  def after_sign_out_path_for(resource)
    root_url
  end
end

Demo/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
    before_action :load_email, only: [:edit, :update, :destroy]

  def index
    @emails = Email.all
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    if @email.save
      redirect_to emails_url, notice: 'New Email is created.'
    else
      render 'new', alert: 'Email cannot be created.'
    end
  end

  def edit
  end

  def update
    if @email.update(email_params)
      redirect_to emails_url, notice: 'Email is updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @email.destroy
      flash[:notice] = 'Email is deleted.'
    else
      flash[:alert] = 'Email cannot be deleted.'
    end
    redirect_to emails_url
  end

  private
  def load_email
    @email = Email.find(params[:id])
  end

  def email_params
    params.require(:email).permit(:subject, :content)
  end

end

Demo/app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :authenticate_mailbox!
  before_action :load_mailbox, only: [:edit, :update, :destroy]

  def index
    @mailboxes = Mailbox.all
  end

  def new
    @mailbox = Mailbox.new
  end

  def create
    @mailbox = Mailbox.new(mailbox_params)
    if @mailbox.save
      redirect_to mailboxes_url, notice: 'New Mailbox is created.'
    else
      render 'new', alert: 'Mailbox cannot be created.'
    end
  end

  def edit
  end

  def update
    if @mailbox.update(mailbox_params)
      redirect_to mailboxes_url, notice: 'Mailbox is updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @mailbox.destroy
      flash[:notice] = 'Mailbox is deleted.'
    else
      flash[:alert] = 'mailbox cannot be deleted.'
    end
    redirect_to mailboxes_url
  end

  private
  def load_mailbox
    @mailbox = Mailbox.find(params[:id])
  end

  def mailbox_params
    params.require(:mailbox).permit(:firstname, :lastname, :email)
  end
end

Demo/app/helpers/application_helper.rb
module ApplicationHelper
end

Demo/app/views/admins/index.html.erb
<div class="container">
  <% if notice %>
      <p><%= notice %></p>
    <% elsif alert %>
      <p><%= alert %></p>
  <% end %>
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <table class="table table-striped table-hover ">
            <thead>
              <tr class="info">
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% Mailbox.all.each do |mailbox| %>
                <tr>
                  <td><%= mailbox.firstname %></td>
                  <td><%= mailbox.lastname %></td>
                  <td><%= mailbox.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

Demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MailerApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">MailerApp</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <% if mailbox_signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to 'New', emails_path %></li>
              <li><%= link_to 'Inbox', emails_path %></li>
              <li><%= link_to 'Spam', emails_path %></li>
              <li><%= link_to 'Contacts', emails_path %></li>
            </ul>
          <% end %>
          <% if mailbox_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
  <%= yield %>
  </body>
</html>

Demo/app/views/mailboxes/_form.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-lg-6">
      <div class="well bs-component">
        <%= form_for @mailbox, html: { class: "form-horizontal" } do |f| %>
          <fieldset>
            <legend>Enter Mailbox details</legend>
            <div class="form-group">
              <%= f.label :firstname, 'Firstname:', class: "col-lg-2 control-label" %>
              <div class="col-lg-10">
                <%= f.text_field :firstname, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :lastname, 'Lastname:', class: "col-lg-2 control-label" %>
              <div class="col-lg-10">
                <%= f.text_field :lastname, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :email, 'Email:', class: "col-lg-2 control-label" %>
              <div class="col-lg-10">
                <%= f.text_field :email, class: "form-control" %>
              </div>
            </div>
            <div class="col-lg-10 col-lg-offset-2">
              <%= f.submit %>  
            </div>
          </fieldset>
        <% end %>
      </div>
    </div>
  </div>
</div>

Demo/app/views/mailboxes/edit.html.erb
<div class="container">
  <h2>Update Mailbox</h2>
  <%= render 'form' %>
  <%= link_to 'Back', mailboxes_path, class: "btn btn-primary btm-sm" %>
</div>

Demo/app/views/mailboxes/index.html.erb
<div class="container">
  <% if notice %>
      <p><%= notice %></p>
    <% elsif alert %>
      <p><%= alert %></p>
  <% end %>
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <div class="bs-component">
          <table class="table table-striped table-hover ">
            <thead>
              <tr class="info">
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @mailboxes.each do |mailbox| %>
                <tr>
                  <td><%= mailbox.firstname %></td>
                  <td><%= mailbox.lastname %></td>
                  <td><%= mailbox.email %></td>
                  <td><%= link_to 'Edit', edit_mailbox_path(mailbox) %></td>
                  <td><%= link_to 'Destroy', mailbox_path(mailbox), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'New Mailbox', new_mailbox_path %>
</div>

Demo/app/views/mailboxes/new.html.erb
<div class="container">
  <h2>New Mailbox</h2>
  <%= render 'form' %>
  <%= link_to 'Back', mailboxes_path, class: "btn btn-primary btm-sm" %>
</div>